#! /usr/bin/env ruby

require "pg"

def list_expenses
  connection = PG.connect(dbname: "expenses")

  result = connection.exec("SELECT * FROM expenses ORDER BY created_on ASC;")
  result.each do |row|
    columns = [row["id"].rjust(3),
               row["created_on"].rjust(10),
               row["amount"].rjust(12),
               row["memo"]]

    puts columns.join(" | ")
  end

  connection.close
end

def display_help
  puts <<~HELP
  Commands:
  
  add AMOUNT MEMO - record a new expense
  clear - delete all expenses
  list - list all expenses
  delete NUMBER - remove expense with id NUMBER
  search QUERY - list expenses with a matching memo field
  HELP
end

def add_expense(amount, memo)
  connection = PG.connect(dbname: "expenses")

  connection.exec("INSERT INTO expenses (amount, memo) VALUES #{amount} \"#{memo}\"")
end

command = ARGV.first

if command == "list"
  list_expenses
elsif command == "add"
  amount = ARGV[1]
  memo = ARGV[2]
  add_expense(amount, memo) if amount && memo
  if amount.nil? || memo.nil?
    puts "You must provide an amount and memo."
  end
else
  display_help
end
